#-------------------- Params --------------------
samplesheet: "/farmshare/home/classes/bios/270/data/samplesheet.csv"

# Option 1: use prebuild Salmon index
index: '/farmshare/home/classes/bios/270/data/indexes/ecoli_transcripts_index'

# OPTION 2: build index from transcriptome (comment out 'index' above if you use this)
# transcriptome: "/farmshare/home/classes/bios/270/data/ecoli_ref/GCF_000401755.1_Escherichia_coli_ATCC_25922_cds_from_genomic.fna"


outdir: '/farmshare/user_data/troy430/bios270/data/processed_data/SRP628437_nf' # modified to new directory for processed data
run_deseq: true
